apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: mb-vault-dev
    cloudName: "AzureCloudPublic"
    objects: |
      array:
        - |
          objectName: dev-cms-pass
          objectType: secret
          objectVersion: ""
    tenantId: d160dbfe-e78f-435d-984b-bc95ab051654