apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-kotlin
  name: spring-kotlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kotlin
  template:
    volumes:
      - name: secrets-az-vault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname-system-msi
    metadata:
      labels:
        app: spring-kotlin
    spec:
      containers:
        - image: rsecrregistry.azurecr.io/springkotlin:0.1.0-SNAPSHOT
          name: springkotlin
          mountVolumes:
          - name: secrets-az-vault
            volumeMount: /mnt/secrets-store
status: {}