apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
- csi-secret.yml
commonLabels:
  app: spring-kotlin
replicas:
- count: 1
  name: spring-kotlin
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newName: rsecrregistry.azurecr.io/springkotlin
  newTag: fed723862b1c4f097ff8844ed0c87195e0f21393
