apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
commonLabels:
  app: spring-kotlin
replicas:
- count: 1
  name: spring-kotlin
images:
- name: springkotlin
  newName: springkotlin
  newTag: aca709883e5912e32eeef09609d5c4c9a9bfc656
