apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
commonLabels:
  app: spring-kotlin
replicas:
- count: 1
  name: spring-kotlin
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newName: rsecrregistry.azurecr.io/springkotlin
  newTag: d0bf22d9f2e7334b632b56a19f23814e8c4c0b57
