apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
replicas:
- count: 1
  name: springkotlin-deployment
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newTag: 63bf9e902f6e9cf396916937ba8da64b9964faf0
