apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
commonLabels:
  app: spring-kotlin
replicas:
- count: 1
  name: spring-kotlin
images:
- name: springkotlin
  newName: rsecrregistry.azurecr.io/springkotlin
  newTag: 714104f853703146b42278f592f513b1b3da0090
