apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
- csi-secret.yml
commonLabels:
  app: spring-kotlin
replicas:
- count: 1
  name: spring-kotlin
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newName: rsecrregistry.azurecr.io/springkotlin
  newTag: 9232a4b47d4913d4354229d96259b055adda943b
