apiVersion: source.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yml
replicas:
- count: 1
  name: springkotlin-deployment
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newTag: ab0a696439af08469f40f8d6a86a41a91076f516
