apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
nameSuffix: -dev
resources:
- deployment.yaml
replicas:
- count: 1
  name: springbootflux-deployment
images:
- name: rsecrregistry.azurecr.io/springkotlin
  newTag: eeb0d470792ba123e73261051a66bbc6b6e30533
