name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONTAINER_REPOSITORY: docker push rafal0823/springkotlin
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}${sha}${ts}" >> "$GITHUB_OUTPUT"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle Wrapper
        id: build-image-with-gradle
        run: |
          ./gradlew bootBuildImage --imageName="$CONTAINER_REPOSITORY:${{ steps.prep.outputs.BUILD_ID }}"

      - name: Login to registry
        uses: docker/login-action@v3
        id: login-to-docker
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker registry
        id: push-image
        run: |
          docker push $CONTAINER_REPOSITORY:${{ steps.prep.outputs.BUILD_ID }}

#      - uses: alexellis/setup-arkade@v1
#      - uses: alexellis/arkade-get@master
#        with:
#          kustomize: latest

#      - name: Kustomize and push
#        id: kustomize
#        working-directory: ./deployment
#        run: |
#          kustomize edit set image $CONTAINER_REPOSITORY=$CONTAINER_REPOSITORY:${{ steps.prep.outputs.BUILD_ID }}
#          git add .
#          git config user.name "Github Action"
#          git config user.email "github-actions@devops-mb.com"
#          git commit -m "Set dev image tag to short sha"
#          git push
